### ISSUE TITLE
Japanese support

### ISSUE THREAD

**Issue by adielcahana** [yannvgn/laserembeddings#28]
How can i  approch towards japanese support on windows?
what kind of issues are there when using the japanese on windows?

Thnaks!!

**Comment by yannvgn** [comment]
Hi @adielcahana,

Japanese support on Windows is back! Please update to v1.1.0 and install the "ja" extra:
```
pip install --upgrade laserembeddings[ja]
```

I had to disable it because [mecab-python3](https://github.com/SamuraiT/mecab-python3/) had no wheels for Windows. Thanks to them for their effort making the wheels available for Windows.

Cheers,

**Comment by adielcahana** [comment]
Thats really great! Thanks!
